# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0002_auto_20180513_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Idcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='idUser',
            new_name='user',
        ),
    ]
