# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0006_adsimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsimages',
            name='ad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='oglasnik.Ad'),
        ),
    ]
