# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oglasnik', '0007_auto_20180526_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oglasnik.Category'),
        ),
    ]
